import { writable } from 'svelte/store';

// Holds whichever dataset is "live" right now: the precomputed Lecture Mode
// JSON, or the output of a just-run Interactive Mode forward pass. Every
// scene and the Token Journey panel read from this one store rather than
// fetching independently, so the two modes are interchangeable at the
// rendering layer (architecture Addendum §1).
export const forwardPassData = writable(null);

/**
 * Lightweight structural check, not a schema library — this project has one
 * data file, hand-generated by one script; a full JSON-schema validator
 * would be more machinery than the actual risk warrants. This just guards
 * against silently rendering a truncated/malformed file with a wall of
 * "undefined" instead of a clear console warning.
 */
function validateForwardPass(json) {
  const problems = [];
  if (!json || typeof json !== 'object') problems.push('root is not an object');
  if (!Array.isArray(json?.stages) || json.stages.length === 0) problems.push('missing/empty "stages" array');
  if (!json?.meta?.sentence || !Array.isArray(json.meta.sentence)) problems.push('missing "meta.sentence"');
  if (!json?.meta?.dModel) problems.push('missing "meta.dModel"');
  if (problems.length) {
    console.warn('[forward-pass.json] structural issues detected — scenes may render incorrectly:', problems);
  }
  return json;
}

export async function loadLectureData() {
  const res = await fetch(`${import.meta.env.BASE_URL}data/forward-pass.json`);
  if (!res.ok) throw new Error(`Failed to load forward-pass.json: ${res.status}`);
  const json = validateForwardPass(await res.json());
  forwardPassData.set(json);
  return json;
}

export function setInteractiveData(computedResult) {
  forwardPassData.set(computedResult);
}
